from __future__ import annotations
import typing
from typing import Any
from enum import IntEnum, IntFlag


class GumToPythonHelpers(typing.Any):
    @staticmethod
    def AsGue(*args: Any, **kwargs: Any) -> Any: ...
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...
