// This code was generated by Gum. Do not modify directly - modifications will
// be lost the next time this file is generated.

using Gum.DataTypes;
using Gum.Managers;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Xml.Serialization;

namespace CodeGen_Skia_ByReference;

internal static class StandardElementsCodeGenRegistration
{
    [ModuleInitializer]
    internal static void RegisterFallbackStandardElements()
    {
        XmlSerializer serializer = GumFileSerializer.GetCompactSerializer(typeof(List<StandardElementSave>));
        string xml = @"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfStandardElementSave xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <StandardElementSave>
    <Name>Circle</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""Blend"" Name=""Blend"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""Blue2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowAlpha"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowBlue"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""DropshadowBlur"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">3</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowGreen"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""DropshadowOffsetX"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""DropshadowOffsetY"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">3</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowRed"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""ExposeChildrenEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillAlpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillBlue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillGreen"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillRed"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientInnerRadius"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">50</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""GradientInnerRadiusUnits"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientOuterRadius"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""GradientOuterRadiusUnits"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""GradientType"" Name=""GradientType"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientX1"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientX1Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientX2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientX2Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientY1"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientY1Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientY2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientY2Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <Variable Type=""int"" Name=""Green2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasDropshadow"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""Height"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">32</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""HeightUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IsFilled"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float?"" Name=""MaxHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MaxWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""Red2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeAlpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeBlue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeGreen"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeRed"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""StrokeWidth"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">2</Value>
      </Variable>
      <Variable Type=""bool"" Name=""UseGradient"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Width"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">32</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""WidthUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>Component</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>Container</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""AutoGridHorizontalCells"" Category=""Children"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">4</Value>
      </Variable>
      <Variable Type=""int"" Name=""AutoGridVerticalCells"" Category=""Children"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">4</Value>
      </Variable>
      <Variable Type=""Blend"" Name=""Blend"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""ChildrenLayout"" Name=""ChildrenLayout"" Category=""Children"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""ClipsChildren"" Category=""Children"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""string"" Name=""ContainedType"" Category=""Children"" SetsValue=""true"" />
      <Variable Type=""bool"" Name=""ExposeChildrenEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""bool"" Name=""FlipHorizontal"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Height"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">150</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""HeightUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IsRenderTarget"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float?"" Name=""MaxHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MaxWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable IsFile=""true"" Type=""string"" Name=""SourceShaderFile"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:string""></Value>
      </Variable>
      <Variable Type=""float"" Name=""StackSpacing"" Category=""Children"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Width"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">150</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""WidthUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""WrapsChildren"" Category=""Children"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>NineSlice</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Animate"" Category=""Animation"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""Blend"" Name=""Blend"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""Blue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""BorderScale"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">1</Value>
      </Variable>
      <Variable Type=""string"" Name=""CurrentChainName"" Category=""Animation"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""CustomFrameTextureCoordinateWidth"" Category=""Source"" SetsValue=""true"" />
      <Variable Type=""bool"" Name=""ExposeChildrenEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""int"" Name=""Green"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""Height"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">64</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""HeightUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IsTilingMiddleSections"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float?"" Name=""MaxHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MaxWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""Red"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable IsFile=""true"" Type=""string"" Name=""SourceFile"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:string""></Value>
      </Variable>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
      <Variable Type=""TextureAddress"" Name=""TextureAddress"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureHeight"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureLeft"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureTop"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureWidth"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Width"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">64</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""WidthUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>Polygon</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""Blue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""Green"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""Red"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfVector2"">
        <Type>Vector2</Type>
        <Name>Points</Name>
        <Category>Points</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value>
          <Vector2>
            <X>0</X>
            <Y>0</Y>
          </Vector2>
          <Vector2>
            <X>32</X>
            <Y>0</Y>
          </Vector2>
          <Vector2>
            <X>32</X>
            <Y>32</Y>
          </Vector2>
          <Vector2>
            <X>0</X>
            <Y>32</Y>
          </Vector2>
          <Vector2>
            <X>0</X>
            <Y>0</Y>
          </Vector2>
        </Value>
      </VariableList>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>Rectangle</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""Blend"" Name=""Blend"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""Blue2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""CornerRadius"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""float?"" Name=""CustomRadiusBottomLeft"" Category=""Rendering"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""CustomRadiusBottomRight"" Category=""Rendering"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""CustomRadiusTopLeft"" Category=""Rendering"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""CustomRadiusTopRight"" Category=""Rendering"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""DropshadowAlpha"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowBlue"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""DropshadowBlur"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">3</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowGreen"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""DropshadowOffsetX"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""DropshadowOffsetY"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">3</Value>
      </Variable>
      <Variable Type=""int"" Name=""DropshadowRed"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""ExposeChildrenEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillAlpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillBlue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillGreen"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""FillRed"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientInnerRadius"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">50</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""GradientInnerRadiusUnits"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientOuterRadius"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""GradientOuterRadiusUnits"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""GradientType"" Name=""GradientType"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientX1"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientX1Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientX2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientX2Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientY1"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientY1Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <Variable Type=""float"" Name=""GradientY2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""GradientY2Units"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <Variable Type=""int"" Name=""Green2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasDropshadow"" Category=""Dropshadow"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""Height"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">50</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""HeightUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IsFilled"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float?"" Name=""MaxHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MaxWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""Red2"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeAlpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeBlue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeGreen"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""StrokeRed"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""StrokeWidth"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">2</Value>
      </Variable>
      <Variable Type=""bool"" Name=""UseGradient"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Width"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">50</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""WidthUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>Sprite</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Animate"" Category=""Animation"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""Blend"" Name=""Blend"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""Blue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""string"" Name=""CurrentChainName"" Category=""Animation"" SetsValue=""true"" />
      <Variable Type=""bool"" Name=""ExposeChildrenEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""FlipHorizontal"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""FlipVertical"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""int"" Name=""Green"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""Height"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""HeightUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">3</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float?"" Name=""MaxHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MaxWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""Red"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""string"" Name=""RenderTargetTextureSource"" Category=""Source"" SetsValue=""true"" />
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable IsFile=""true"" Type=""string"" Name=""SourceFile"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:string""></Value>
      </Variable>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
      <Variable Type=""TextureAddress"" Name=""TextureAddress"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureHeight"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""TextureHeightScale"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">1</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureLeft"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureTop"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""int"" Name=""TextureWidth"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""TextureWidthScale"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">1</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Width"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""WidthUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">3</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Wrap"" Category=""Source"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
  <StandardElementSave>
    <Name>Text</Name>
    <State>
      <Name>Default</Name>
      <Variable Type=""int"" Name=""Alpha"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""int"" Name=""Blue"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable IsFile=""true"" Type=""string"" Name=""CustomFontFile"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:string""></Value>
      </Variable>
      <Variable Type=""bool"" Name=""ExposeChildrenEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable IsFont=""true"" Type=""string"" Name=""Font"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:string"">Arial</Value>
      </Variable>
      <Variable Type=""float"" Name=""FontScale"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">1</Value>
      </Variable>
      <Variable Type=""int"" Name=""FontSize"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">18</Value>
      </Variable>
      <Variable Type=""int"" Name=""Green"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""bool"" Name=""HasEvents"" Category=""Behavior"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""Height"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">50</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""HeightUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""HorizontalAlignment"" Category=""Text"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IgnoredByParentSize"" Category=""Parent"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IsBold"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""IsItalic"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""float"" Name=""LineHeightMultiplier"" Category=""Text"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">1</Value>
      </Variable>
      <Variable Type=""float?"" Name=""MaxHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""int?"" Name=""MaxLettersToShow"" Category=""Text"" SetsValue=""true"" />
      <Variable Type=""int?"" Name=""MaxNumberOfLines"" Category=""Text"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MaxWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinHeight"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""float?"" Name=""MinWidth"" Category=""Dimensions"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""OutlineThickness"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""string"" Name=""Parent"" Category=""Parent"" SetsValue=""true"" />
      <Variable Type=""int"" Name=""Red"" Category=""Rendering"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">255</Value>
      </Variable>
      <Variable Type=""float"" Name=""Rotation"" Category=""Flip and Rotation"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""State"" Name=""State"" Category=""States and Visibility"" SetsValue=""false"">
        <Value xsi:type=""xsd:string"">Default</Value>
      </Variable>
      <Variable Type=""string"" Name=""Text"" Category=""Text"" SetsValue=""true"">
        <Value xsi:type=""xsd:string"">Hello</Value>
      </Variable>
      <Variable Type=""TextOverflowHorizontalMode"" Name=""TextOverflowHorizontalMode"" Category=""Text"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""TextOverflowVerticalMode"" Name=""TextOverflowVerticalMode"" Category=""Text"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""UseCustomFont"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">false</Value>
      </Variable>
      <Variable Type=""bool"" Name=""UseFontSmoothing"" Category=""Font"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""VerticalAlignment"" Category=""Text"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""bool"" Name=""Visible"" Category=""States and Visibility"" SetsValue=""true"">
        <Value xsi:type=""xsd:boolean"">true</Value>
      </Variable>
      <Variable Type=""float"" Name=""Width"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">100</Value>
      </Variable>
      <Variable Type=""DimensionUnitType"" Name=""WidthUnits"" Category=""Dimensions"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""X"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""HorizontalAlignment"" Name=""XOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""XUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""float"" Name=""Y"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:float"">0</Value>
      </Variable>
      <Variable Type=""VerticalAlignment"" Name=""YOrigin"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">0</Value>
      </Variable>
      <Variable Type=""PositionUnitType"" Name=""YUnits"" Category=""Position"" SetsValue=""true"">
        <Value xsi:type=""xsd:int"">1</Value>
      </Variable>
      <VariableList xsi:type=""VariableListSaveOfString"">
        <Type>string</Type>
        <Name>VariableReferences</Name>
        <Category>References</Category>
        <IsFile>false</IsFile>
        <IsHiddenInPropertyGrid>false</IsHiddenInPropertyGrid>
        <Value />
      </VariableList>
    </State>
    <Behaviors />
  </StandardElementSave>
</ArrayOfStandardElementSave>";
        using StringReader reader = new StringReader(xml);
        List<StandardElementSave> standards = (List<StandardElementSave>)serializer.Deserialize(reader);
        foreach (StandardElementSave standard in standards)
        {
            standard.Initialize(defaultState: null, tolerateMissingDefaultStates: true);
        }
        ObjectFinder.Self.RegisterFallbackStandardElements(standards);
    }
}
