<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
		<LangVersion>12.0</LangVersion>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Gum.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.ComponentModel.Composition" Version="9.0.3" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<PluginOutputFiles Include="$(TargetPath)" />
			<PluginOutputFiles Include="$(TargetDir)$(TargetName).pdb" />
		</ItemGroup>
		<Copy SourceFiles="@(PluginOutputFiles)" DestinationFolder="$(SolutionDir)Gum/bin/$(ConfigurationName)/Plugins/$(TargetName)" />
	</Target>
</Project>
