using Gum.GueDeriving;
using Microsoft.Xna.Framework.Graphics;
using RenderingLibrary.Graphics;

namespace MonoGameGumImmediateMode.Screens
{
    /// <summary>
    /// Demonstrates rendering a <see cref="TextRuntime"/> through GumBatch. Unlike
    /// <c>DrawString</c>, TextRuntime supports wrapping, alignment, rotation, and
    /// other Gum layout rules. The font is generated by KernSmith on demand based
    /// on the <see cref="TextRuntime.Font"/> and <see cref="TextRuntime.FontSize"/>
    /// properties — no .fnt file required.
    /// </summary>
    public class TextRuntimeScreen : IImmediateModeScreen
    {
        private TextRuntime _wrappedText;
        private TextRuntime _rotatedText;

        public void Initialize(GraphicsDevice graphicsDevice)
        {
            _wrappedText = new TextRuntime();
            _wrappedText.Font = "Arial";
            _wrappedText.FontSize = 16;
            _wrappedText.Text =
                "This TextRuntime wraps within its 280-pixel width. " +
                "KernSmith generated the font in memory the first time it was used.";
            _wrappedText.X = 20;
            _wrappedText.Y = 80;
            _wrappedText.Width = 280;
            _wrappedText.WidthUnits = Gum.DataTypes.DimensionUnitType.Absolute;
            _wrappedText.Height = 0;
            _wrappedText.HeightUnits = Gum.DataTypes.DimensionUnitType.RelativeToChildren;

            _rotatedText = new TextRuntime();
            _rotatedText.Font = "Arial";
            _rotatedText.FontSize = 20;
            _rotatedText.IsBold = true;
            _rotatedText.Text = "Rotated, bold, 20pt — also via KernSmith";
            _rotatedText.X = 500;
            _rotatedText.Y = 220;
            _rotatedText.Rotation = 30;
        }

        public void Draw(GumBatch gumBatch, SpriteBatch spriteBatch)
        {
            gumBatch.Begin();
            gumBatch.Draw(_wrappedText);
            gumBatch.Draw(_rotatedText);
            gumBatch.End();
        }

        public void Dispose()
        {
        }
    }
}
