from __future__ import annotations
import typing
from typing import Any
from enum import IntEnum, IntFlag


class ElementSaveExtensions(typing.Any):
    @property
    def CustomCreateGraphicalComponentFunc(self) -> Any: ...
    @CustomCreateGraphicalComponentFunc.setter
    def CustomCreateGraphicalComponentFunc(self, value: Any) -> None: ...
    @staticmethod
    def RegisterGueInstantiationType(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def RegisterGueInstantiation(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def RegisterDefaultInstantiationType(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def CreateGueForElement(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def ToGraphicalUiElement(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def SetStatesAndCategoriesRecursively(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def AddStatesAndCategoriesRecursivelyToGue(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def CreateGraphicalComponent(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def AddExposedVariablesRecursively(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def SetVariablesRecursively(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def ValueEquality(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def ApplyVariableReferences(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def ApplyVariableReferences(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def ApplyVariableReferencesOnSpecificOwner(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def GetRightSideAndState(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def SetGraphicalUiElement(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def CreateChildrenRecursively(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def Reset(*args: Any, **kwargs: Any) -> Any: ...
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...

class InstanceSaveExtensionMethods(typing.Any):
    @staticmethod
    def ToGraphicalUiElement(*args: Any, **kwargs: Any) -> Any: ...
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...

class VariableReferenceAssignmentResult(typing.Any):
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...

class <>c(typing.Any):
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...

class <>c__DisplayClass23_0(typing.Any):
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...

class <>c__DisplayClass25_0(typing.Any):
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...

class <>c__DisplayClass29_0(typing.Any):
    def GetType(self, *args: Any, **kwargs: Any) -> Any: ...
    def ToString(self, *args: Any, **kwargs: Any) -> Any: ...
    def Equals(self, *args: Any, **kwargs: Any) -> Any: ...
    def GetHashCode(self, *args: Any, **kwargs: Any) -> Any: ...
