from __future__ import annotations
import typing
from typing import Any


class PositionUnitType(int): ...

class ReferenceType(int): ...

class TypedElementReference(typing.Any):
    OwnerOfReferencingObject: typing.Any  # property
    StateSave: typing.Any  # property
    ReferencingObject: typing.Any  # property
    ReferenceType: typing.Any  # property
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class IObjectFinder(typing.Any):
    GumProjectSave: typing.Any  # property
    def GetElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetBaseElements(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class ObjectFinder(typing.Any):
    Self: typing.Any  # property
    GumProjectSave: typing.Any  # property
    def ForceResetCache(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def EnableCache(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def DisableCache(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetScreen(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetComponent(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetComponent(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetStandardElement(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementsReferencing(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementsReferencing(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementsReferencingRecursively(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetBehaviorContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementsReferencing(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetRootStandardElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetRootStandardElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementsInheritingFrom(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetBaseElements(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetAllFilesInProject(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetFilesReferencedBy(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetInstanceRecursively(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetDefaultChildName(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetBehavior(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetBehavior(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementReferencesToThis(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementsReferencedByThis(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetRootVariable(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetRootVariableList(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetRootVariableList(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetRootVariable(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetElementContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetStateContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetContainerOf(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def IsVariableOrphaned(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def IsInstanceRecursivelyReferencingElement(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class InstanceExtensionMethods(typing.Any):
    def GetBaseElementSave(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetParentInstance(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetSiblingsIncludingThis(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class ObjectFinderExt(typing.Any):
    def IsProjectSaved(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class TextureAddress(int): ...

class ChildrenLayout(int): ...

class StandardElementsManager(typing.Any):
    DefaultTypes: typing.Any  # property
    Self: typing.Any  # property
    DefaultType: typing.Any  # property
    DefaultStates: typing.Any  # property
    def Initialize(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def RefreshDefaults(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def AddClipsChildren(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def AddEventVariables(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def AddColorVariables(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def AddDimensionsVariables(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def AddPositioningVariables(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetDefaultStateFor(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def IsDefaultType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def PopulateProjectWithDefaultStandards(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def AddStandardElementSaveInstance(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass19_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass26_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass30_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass38_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass42_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass46_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass48_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass52_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <>c__DisplayClass1_0(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class DimensionVariableAction(int): ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...

class <get_DefaultTypes>d__5(typing.Any):
    def Equals(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kw: typing.Any) -> typing.Any: ...
