from __future__ import annotations
import typing
from typing import Any


class TagInfo(typing.Any):
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class FoundTag(typing.Any):
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class BbCodeParser(typing.Any):
    def Parse(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddTags(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RemoveTags(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class BindingContextChangedEventArgs(typing.Any):
    OldBindingContext: typing.Any
    NewBindingContext: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class BindableGue(typing.Any):
    BindingContext: typing.Any
    BindingContextBindingPropertyOwner: typing.Any
    BindingContextBinding: typing.Any
    IsFontDirty: typing.Any
    IsLayoutSuspended: typing.Any
    Categories: typing.Any
    StackedRowOrColumnIndex: typing.Any
    StackedRowOrColumnDimensions: typing.Any
    ElementSave: typing.Any
    Managers: typing.Any
    EffectiveManagers: typing.Any
    Visible: typing.Any
    Z: typing.Any
    Layer: typing.Any
    IsRenderTarget: typing.Any
    Alpha: typing.Any
    XUnits: typing.Any
    YUnits: typing.Any
    XOrigin: typing.Any
    YOrigin: typing.Any
    WidthUnits: typing.Any
    HeightUnits: typing.Any
    IgnoredByParentSize: typing.Any
    ChildrenLayout: typing.Any
    AutoGridHorizontalCells: typing.Any
    AutoGridVerticalCells: typing.Any
    TextOverflowVerticalMode: typing.Any
    StackSpacing: typing.Any
    UseFixedStackChildrenSize: typing.Any
    Rotation: typing.Any
    FlipHorizontal: typing.Any
    X: typing.Any
    Y: typing.Any
    MaxWidth: typing.Any
    MinWidth: typing.Any
    Width: typing.Any
    MaxHeight: typing.Any
    MinHeight: typing.Any
    Height: typing.Any
    Parent: typing.Any
    ParentGue: typing.Any
    ElementGueContainingThis: typing.Any
    EffectiveParentGue: typing.Any
    RenderableComponent: typing.Any
    ContainedElements: typing.Any
    Name: typing.Any
    Children: typing.Any
    Tag: typing.Any
    Component: typing.Any
    AbsoluteX: typing.Any
    AbsoluteLeft: typing.Any
    AbsoluteY: typing.Any
    AbsoluteTop: typing.Any
    AbsoluteRight: typing.Any
    AbsoluteBottom: typing.Any
    ExplicitIVisibleParent: typing.Any
    TextureTop: typing.Any
    TextureLeft: typing.Any
    TextureWidth: typing.Any
    TextureHeight: typing.Any
    TextureWidthScale: typing.Any
    TextureHeightScale: typing.Any
    TextureAddress: typing.Any
    Wrap: typing.Any
    WrapsChildren: typing.Any
    ClipsChildren: typing.Any
    Animations: typing.Any
    IsFullyCreated: typing.Any
    UseCustomFont: typing.Any
    CustomFontFile: typing.Any
    Font: typing.Any
    FontSize: typing.Any
    IsItalic: typing.Any
    IsBold: typing.Any
    UseFontSmoothing: typing.Any
    OutlineThickness: typing.Any
    def RemoveFromManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetBinding(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ConvertValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateFontRecursive(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateToFontValues(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AnimateSelf(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateTextureValuesFrom(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PlayAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def StopAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetContainedObject(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def CreateChildrenRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Clone(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateHeight(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateWidth(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetIfDimensionsDependOnChildren(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentOffsets(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Dock(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetDock(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Anchor(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAnchor(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AfterFullCreation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetInitialState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PreRender(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetGueValues(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddExposedVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsExposedVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def MoveToLayer(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetProperty(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyStateRecursive(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddCategory(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddStates(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def InterpolateBetween(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsPointInside(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SuspendLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ClearDirtyLayoutState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ResumeLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddChild(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetGraphicalUiElementByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetGraphicalUiElementByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByNameRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentByNameRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FillListWithChildrenByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FillListWithChildrenByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RefreshTextOverflowVerticalMode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAbsoluteWidth(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAbsoluteHeight(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Render(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class RoutedEventArgs(typing.Any):
    Handled: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class InputEventArgs(typing.Any):
    InputDevice: typing.Any
    Handled: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class SelectionChangedEventArgs(typing.Any):
    RemovedItems: typing.Any
    AddedItems: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class InteractiveGue(typing.Any):
    CurrentGameTime: typing.Any
    CurrentInputReceiver: typing.Any
    HasEvents: typing.Any
    ExposeChildrenEvents: typing.Any
    RaiseChildrenEventsOutsideOfBounds: typing.Any
    IsEnabled: typing.Any
    FormsControlAsObject: typing.Any
    BindingContext: typing.Any
    BindingContextBindingPropertyOwner: typing.Any
    BindingContextBinding: typing.Any
    IsFontDirty: typing.Any
    IsLayoutSuspended: typing.Any
    Categories: typing.Any
    StackedRowOrColumnIndex: typing.Any
    StackedRowOrColumnDimensions: typing.Any
    ElementSave: typing.Any
    Managers: typing.Any
    EffectiveManagers: typing.Any
    Visible: typing.Any
    Z: typing.Any
    Layer: typing.Any
    IsRenderTarget: typing.Any
    Alpha: typing.Any
    XUnits: typing.Any
    YUnits: typing.Any
    XOrigin: typing.Any
    YOrigin: typing.Any
    WidthUnits: typing.Any
    HeightUnits: typing.Any
    IgnoredByParentSize: typing.Any
    ChildrenLayout: typing.Any
    AutoGridHorizontalCells: typing.Any
    AutoGridVerticalCells: typing.Any
    TextOverflowVerticalMode: typing.Any
    StackSpacing: typing.Any
    UseFixedStackChildrenSize: typing.Any
    Rotation: typing.Any
    FlipHorizontal: typing.Any
    X: typing.Any
    Y: typing.Any
    MaxWidth: typing.Any
    MinWidth: typing.Any
    Width: typing.Any
    MaxHeight: typing.Any
    MinHeight: typing.Any
    Height: typing.Any
    Parent: typing.Any
    ParentGue: typing.Any
    ElementGueContainingThis: typing.Any
    EffectiveParentGue: typing.Any
    RenderableComponent: typing.Any
    ContainedElements: typing.Any
    Name: typing.Any
    Children: typing.Any
    Tag: typing.Any
    Component: typing.Any
    AbsoluteX: typing.Any
    AbsoluteLeft: typing.Any
    AbsoluteY: typing.Any
    AbsoluteTop: typing.Any
    AbsoluteRight: typing.Any
    AbsoluteBottom: typing.Any
    ExplicitIVisibleParent: typing.Any
    TextureTop: typing.Any
    TextureLeft: typing.Any
    TextureWidth: typing.Any
    TextureHeight: typing.Any
    TextureWidthScale: typing.Any
    TextureHeightScale: typing.Any
    TextureAddress: typing.Any
    Wrap: typing.Any
    WrapsChildren: typing.Any
    ClipsChildren: typing.Any
    Animations: typing.Any
    IsFullyCreated: typing.Any
    UseCustomFont: typing.Any
    CustomFontFile: typing.Any
    Font: typing.Any
    FontSize: typing.Any
    IsItalic: typing.Any
    IsBold: typing.Any
    UseFontSmoothing: typing.Any
    OutlineThickness: typing.Any
    def CallClick(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallRollOff(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallDragging(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallRemoveAsPushed(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallRollOn(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallRollOver(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallHoverOver(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def TryCallPush(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def HasCursorOver(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsInParentChain(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddNextPushAction(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddNextClickAction(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RemoveFromManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetBinding(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateFontRecursive(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateToFontValues(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AnimateSelf(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateTextureValuesFrom(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PlayAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def StopAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetContainedObject(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def CreateChildrenRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Clone(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateHeight(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateWidth(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetIfDimensionsDependOnChildren(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentOffsets(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Dock(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetDock(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Anchor(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAnchor(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AfterFullCreation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetInitialState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PreRender(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetGueValues(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddExposedVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsExposedVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def MoveToLayer(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetProperty(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyStateRecursive(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddCategory(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddStates(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def InterpolateBetween(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsPointInside(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SuspendLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ClearDirtyLayoutState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ResumeLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddChild(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetGraphicalUiElementByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetGraphicalUiElementByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByNameRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentByNameRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FillListWithChildrenByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FillListWithChildrenByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RefreshTextOverflowVerticalMode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAbsoluteWidth(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAbsoluteHeight(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Render(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class IInputReceiver(typing.Any):
    ParentInputReceiver: typing.Any
    def OnGainFocus(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def OnLoseFocus(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def OnFocusUpdate(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def OnFocusUpdatePreview(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def DoKeyboardAction(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class InputDevice(int): ...

class Cursors(int): ...

class ICursor(typing.Any):
    CustomCursor: typing.Any
    LastInputDevice: typing.Any
    X: typing.Any
    Y: typing.Any
    LastPrimaryPushTime: typing.Any
    LastPrimaryClickTime: typing.Any
    XChange: typing.Any
    YChange: typing.Any
    ScrollWheelChange: typing.Any
    ZVelocity: typing.Any
    PrimaryPush: typing.Any
    PrimaryDown: typing.Any
    PrimaryClick: typing.Any
    PrimaryClickNoSlide: typing.Any
    PrimaryDoubleClick: typing.Any
    PrimaryDoublePush: typing.Any
    SecondaryPush: typing.Any
    SecondaryDown: typing.Any
    SecondaryClick: typing.Any
    SecondaryDoubleClick: typing.Any
    MiddlePush: typing.Any
    MiddleDown: typing.Any
    MiddleClick: typing.Any
    MiddleDoubleClick: typing.Any
    WindowPushed: typing.Any
    WindowOver: typing.Any
    def XRespectingGumZoomAndBounds(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def YRespectingGumZoomAndBounds(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class IInputReceiverKeyboard(typing.Any):
    IsShiftDown: typing.Any
    IsCtrlDown: typing.Any
    IsAltDown: typing.Any
    def GetStringTyped(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class HandledActions(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class GueInteractiveExtensionMethods(typing.Any):
    def DoUiActivityRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def DoUiActivityRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class MissingFileBehavior(int): ...

class Anchor(int): ...

class Dock(int): ...

class GraphicalUiElement(typing.Any):
    IsFontDirty: typing.Any
    IsLayoutSuspended: typing.Any
    Categories: typing.Any
    StackedRowOrColumnIndex: typing.Any
    StackedRowOrColumnDimensions: typing.Any
    MissingFileBehavior: typing.Any
    ElementSave: typing.Any
    Managers: typing.Any
    EffectiveManagers: typing.Any
    Visible: typing.Any
    CanvasWidth: typing.Any
    CanvasHeight: typing.Any
    Z: typing.Any
    Layer: typing.Any
    IsRenderTarget: typing.Any
    Alpha: typing.Any
    XUnits: typing.Any
    YUnits: typing.Any
    XOrigin: typing.Any
    YOrigin: typing.Any
    WidthUnits: typing.Any
    HeightUnits: typing.Any
    IgnoredByParentSize: typing.Any
    ChildrenLayout: typing.Any
    AutoGridHorizontalCells: typing.Any
    AutoGridVerticalCells: typing.Any
    TextOverflowVerticalMode: typing.Any
    StackSpacing: typing.Any
    UseFixedStackChildrenSize: typing.Any
    Rotation: typing.Any
    FlipHorizontal: typing.Any
    X: typing.Any
    Y: typing.Any
    MaxWidth: typing.Any
    MinWidth: typing.Any
    Width: typing.Any
    MaxHeight: typing.Any
    MinHeight: typing.Any
    Height: typing.Any
    Parent: typing.Any
    ParentGue: typing.Any
    ElementGueContainingThis: typing.Any
    EffectiveParentGue: typing.Any
    RenderableComponent: typing.Any
    ContainedElements: typing.Any
    Name: typing.Any
    Children: typing.Any
    Tag: typing.Any
    Component: typing.Any
    AbsoluteX: typing.Any
    AbsoluteLeft: typing.Any
    AbsoluteY: typing.Any
    AbsoluteTop: typing.Any
    AbsoluteRight: typing.Any
    AbsoluteBottom: typing.Any
    ExplicitIVisibleParent: typing.Any
    TextureTop: typing.Any
    TextureLeft: typing.Any
    TextureWidth: typing.Any
    TextureHeight: typing.Any
    TextureWidthScale: typing.Any
    TextureHeightScale: typing.Any
    TextureAddress: typing.Any
    Wrap: typing.Any
    WrapsChildren: typing.Any
    ClipsChildren: typing.Any
    Animations: typing.Any
    IsFullyCreated: typing.Any
    AreUpdatesAppliedWhenInvisible: typing.Any
    UseCustomFont: typing.Any
    CustomFontFile: typing.Any
    Font: typing.Any
    FontSize: typing.Any
    IsItalic: typing.Any
    IsBold: typing.Any
    UseFontSmoothing: typing.Any
    OutlineThickness: typing.Any
    def UpdateFontRecursive(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateToFontValues(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AnimateSelf(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateTextureValuesFrom(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PlayAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def StopAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetContainedObject(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def CreateChildrenRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Clone(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateHeight(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def UpdateWidth(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetIfDimensionsDependOnChildren(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentOffsets(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Dock(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetDock(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Anchor(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAnchor(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AfterFullCreation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetInitialState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PreRender(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetGueValues(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddExposedVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsExposedVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def MoveToLayer(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RemoveFromManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetPropertyThroughReflection(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetProperty(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyStateRecursive(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddCategory(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddStates(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def InterpolateBetween(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsPointInside(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SuspendLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ClearDirtyLayoutState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ResumeLayout(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddChild(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetGraphicalUiElementByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetGraphicalUiElementByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByNameRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetChildByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentByNameRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetParentByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FillListWithChildrenByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FillListWithChildrenByTypeRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RefreshTextOverflowVerticalMode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAbsoluteWidth(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAbsoluteHeight(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Render(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class GraphicalUiElementExtensions(typing.Any):
    def ApplyAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PlayAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def PlayAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetAnimation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class IManagedObject(typing.Any):
    def AddToManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RemoveFromManagers(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ElementWithState(typing.Any):
    Element: typing.Any
    StateName: typing.Any
    CategorizedStates: typing.Any
    InstanceName: typing.Any
    StateSave: typing.Any
    AllStates: typing.Any
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ElementWithStateExtensionMethods(typing.Any):
    def Add(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Remove(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class Tag(typing.Any):
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass1_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VmToUiProperty(typing.Any):
    Unassigned: typing.Any
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass37_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass42_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <GetAllBindableDescendants>d__44(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ChildType(int): ...

class DirtyState(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ParentUpdateType(int): ...

class ParentChangedEventArgs(typing.Any):
    OldValue: typing.Any
    NewValue: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass324_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass380_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass381_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass382_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass383_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass384_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass6_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass21_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <get_AllStates>d__21(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass1_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
