using CommunityToolkit.Mvvm.Input;
using Gum.Commands;
using Gum.DataTypes;
using Gum.Managers;
using Gum.ProjectServices.CodeGeneration;
using Gum.Services.Dialogs;
using System;
using System.Collections.Generic;
using System.Linq;

namespace OrphanCodeFilePlugin;

/// <summary>
/// Business logic behind the tool's orphaned-code-file reporting, kept out of the WPF-hosted
/// <c>MainOrphanCodeFilePlugin</c> (mirrors <see cref="ConvertToJsonPlugin.ConvertToJsonLogic"/>)
/// so it can be unit tested headlessly. Holds the most recent scan result, turns it into Errors tab
/// entries, and resolves an entry by moving the file to the Recycle Bin.
/// </summary>
public class OrphanCodeFileReporter
{
    /// <summary>
    /// Error code for an orphaned code file, registered in the docs registry so the Errors tab can
    /// link to the explanation of what orphans are and why the scan is best effort.
    /// </summary>
    public const string ErrorCode = "GUM0005";

    private readonly IOrphanCodeFileScanService _scanService;
    private readonly IFileCommands _fileCommands;
    private readonly IDialogService _dialogService;
    private readonly List<OrphanCodeFile> _orphans;

    public OrphanCodeFileReporter(
        IOrphanCodeFileScanService scanService,
        IFileCommands fileCommands,
        IDialogService dialogService)
    {
        _scanService = scanService;
        _fileCommands = fileCommands;
        _dialogService = dialogService;
        _orphans = new List<OrphanCodeFile>();
    }

    /// <summary>
    /// The orphans found by the most recent <see cref="Refresh"/>, minus any already resolved.
    /// </summary>
    public IReadOnlyList<OrphanCodeFile> Orphans => _orphans;

    /// <summary>
    /// Raised whenever <see cref="Orphans"/> changes, so the host can refresh whatever displays it.
    /// </summary>
    public event Action? OrphansChanged;

    /// <summary>
    /// Re-runs the scan and replaces <see cref="Orphans"/>. Clears the list when no project is
    /// loaded. Read-only — nothing is deleted until <see cref="Resolve"/> is called.
    /// </summary>
    public void Refresh(GumProjectSave? project, CodeOutputProjectSettings projectSettings)
    {
        _orphans.Clear();

        if (project != null)
        {
            _orphans.AddRange(_scanService.Scan(project, projectSettings));
        }

        OrphansChanged?.Invoke();
    }

    /// <summary>
    /// Builds one Errors tab entry per orphan, each carrying an action that resolves it.
    /// </summary>
    public IEnumerable<ErrorViewModel> CreateErrors() =>
        _orphans.ToList().Select(orphan => new ErrorViewModel
        {
            Code = ErrorCode,
            Message = $"Orphaned {GetKindDescription(orphan.Kind)}, no matching element in the project: " +
                $"{orphan.FilePath.FullPath}",
            ActionName = "Delete File",
            ActionCommand = new RelayCommand(() => Resolve(orphan))
        });

    /// <summary>
    /// Moves an orphaned file to the Recycle Bin and drops it from <see cref="Orphans"/>. A generated
    /// file goes immediately — it is a pure function of its element, so removing it is lossless.
    /// Anything else is user-authored or hand-configured, so it is confirmed first.
    /// </summary>
    public void Resolve(OrphanCodeFile orphan)
    {
        if (orphan.Kind != OrphanCodeFileKind.Generated)
        {
            bool confirmed = _dialogService.ShowYesNoMessage(
                $"{orphan.FilePath.FullPath}\n\nThis file is not regenerated by Gum, so removing it loses " +
                "anything it contains. Move it to the Recycle Bin?",
                "Delete Orphaned File?");

            if (!confirmed)
            {
                return;
            }
        }

        _fileCommands.MoveToRecycleBin(orphan.FilePath);
        _orphans.Remove(orphan);
        OrphansChanged?.Invoke();
    }

    private static string GetKindDescription(OrphanCodeFileKind kind) => kind switch
    {
        OrphanCodeFileKind.Generated => "generated code file",
        OrphanCodeFileKind.CustomCode => "custom code file",
        _ => "element code settings file"
    };
}
