from __future__ import annotations
import typing
from typing import Any


class ComponentSave(typing.Any):
    DefaultChildContainer: typing.Any
    FileExtension: typing.Any
    Subfolder: typing.Any
    Name: typing.Any
    StrippedName: typing.Any
    BaseType: typing.Any
    FileName: typing.Any
    States: typing.Any
    Categories: typing.Any
    Instances: typing.Any
    Events: typing.Any
    DefaultState: typing.Any
    IsSourceFileMissing: typing.Any
    AllStates: typing.Any
    Behaviors: typing.Any
    def Clone(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetInstance(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Save(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class CustomPropertySave(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class CustomPropertySaveListExtensions(typing.Any):
    def ContainsValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Remove(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class DimensionUnitType(int): ...

class HierarchyDependencyType(int): ...

class DimensionUnitTypeExtensions(typing.Any):
    def GetIsPixelBased(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetDependencyType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ElementType(int): ...

class LinkType(int): ...

class ElementReference(typing.Any):
    ElementType: typing.Any
    LinkType: typing.Any
    Extension: typing.Any
    Subfolder: typing.Any
    Link: typing.Any
    def ToElementSave(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ElementSave(typing.Any):
    Name: typing.Any
    StrippedName: typing.Any
    BaseType: typing.Any
    FileName: typing.Any
    States: typing.Any
    Categories: typing.Any
    Instances: typing.Any
    Events: typing.Any
    Subfolder: typing.Any
    FileExtension: typing.Any
    DefaultState: typing.Any
    IsSourceFileMissing: typing.Any
    AllStates: typing.Any
    Behaviors: typing.Any
    def GetInstance(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Save(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class EventSave(typing.Any):
    Name: typing.Any
    Enabled: typing.Any
    ExposedAsName: typing.Any
    def GetExposedOrRootName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetRootName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetSourceObject(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class GuideRectangle(typing.Any):
    X: typing.Any
    Y: typing.Any
    Width: typing.Any
    Height: typing.Any
    Name: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class LinkLoadingPreference(int): ...

class GumLoadResult(typing.Any):
    ErrorMessage: typing.Any
    MissingFiles: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class GumProjectSave(typing.Any):
    FontRanges: typing.Any
    FontSpacingVertical: typing.Any
    FontSpacingHorizontal: typing.Any
    Version: typing.Any
    DefaultCanvasWidth: typing.Any
    DefaultCanvasHeight: typing.Any
    ShowOutlines: typing.Any
    ShowCanvasOutline: typing.Any
    ShowRuler: typing.Any
    ShowCheckerBackground: typing.Any
    TextureFilter: typing.Any
    ConvertVariablesOnUnitTypeChange: typing.Any
    RestrictToUnitValues: typing.Any
    RestrictFileNamesForAndroid: typing.Any
    Guides: typing.Any
    ParentProjectRoot: typing.Any
    LocalizationFile: typing.Any
    ShowLocalizationInGum: typing.Any
    CurrentLanguageIndex: typing.Any
    FullFileName: typing.Any
    Screens: typing.Any
    Components: typing.Any
    StandardElements: typing.Any
    Behaviors: typing.Any
    ElementAnimations: typing.Any
    AllElements: typing.Any
    ScreenReferences: typing.Any
    ComponentReferences: typing.Any
    StandardElementReferences: typing.Any
    BehaviorReferences: typing.Any
    SinglePixelTextureFile: typing.Any
    SinglePixelTextureTop: typing.Any
    SinglePixelTextureLeft: typing.Any
    SinglePixelTextureRight: typing.Any
    SinglePixelTextureBottom: typing.Any
    def Load(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Load(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Load(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetScreenSave(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetComponentSave(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetStandardElementSave(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ReloadBehavior(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ReloadElement(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Save(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SaveStandardElements(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ReactToRenamed(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class IInstanceContainer(typing.Any):
    Name: typing.Any
    Instances: typing.Any

class InstanceSave(typing.Any):
    Locked: typing.Any
    ParentContainer: typing.Any
    def ShouldSerializeLocked(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Clone(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class IStateContainer(typing.Any):
    UncategorizedStates: typing.Any
    AllStates: typing.Any
    Categories: typing.Any

class NamedRectangle(typing.Any):
    X: typing.Any
    Y: typing.Any
    Width: typing.Any
    Height: typing.Any
    Name: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ScreenSave(typing.Any):
    FileExtension: typing.Any
    Subfolder: typing.Any
    Name: typing.Any
    StrippedName: typing.Any
    BaseType: typing.Any
    FileName: typing.Any
    States: typing.Any
    Categories: typing.Any
    Instances: typing.Any
    Events: typing.Any
    DefaultState: typing.Any
    IsSourceFileMissing: typing.Any
    AllStates: typing.Any
    Behaviors: typing.Any
    def Clone(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetInstance(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Save(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class StandardElementTypes(int): ...

class StandardElementSave(typing.Any):
    FileExtension: typing.Any
    Subfolder: typing.Any
    Name: typing.Any
    StrippedName: typing.Any
    BaseType: typing.Any
    FileName: typing.Any
    States: typing.Any
    Categories: typing.Any
    Instances: typing.Any
    Events: typing.Any
    DefaultState: typing.Any
    IsSourceFileMissing: typing.Any
    AllStates: typing.Any
    Behaviors: typing.Any
    def GetInstance(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Save(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class BehaviorSaveExtensionMethods(typing.Any):
    def Initialize(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ComponentSaveExtensionMethods(typing.Any):
    def IsOfType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def InitializeDefaultAndComponentVariables(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VariableSaveSorter(typing.Any):
    ListOrderToMatch: typing.Any
    def Compare(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IndexOfByName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class ElementSaveExtensionMethods(typing.Any):
    def Initialize(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ContainsName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsOfType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetStateSaveRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetStateSaveCategoryRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetStateSaveCategoryRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class InstanceStatePair(typing.Any):
    InstanceSave: typing.Any
    VariableName: typing.Any
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class InstanceSaveExtensionMethods(typing.Any):
    def IsParentASibling(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Initialize(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsComponent(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetVariableFromThisOrBase(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetVariableFromThisOrBase(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetVariableListFromThisOrBase(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetValueFromThisOrBase(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsOfType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class GumProjectSaveExtensionMethods(typing.Any):
    def Initialize(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SortElementAndBehaviors(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddNewStandardElementTypes(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RemoveDuplicateVariables(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FixStandardVariables(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class PluginSettingsSave(typing.Any):
    DisabledPlugins: typing.Any
    def Load(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Save(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class RecursiveVariableFinder(typing.Any):
    InstanceSave: typing.Any
    ElementStack: typing.Any
    ContainerType: typing.Any
    def GetValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetValue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetVariable(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetVariableList(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetExposedVariablesForThisInstance(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetValueByBottomName(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VariableSaveExtensionMethods(typing.Any):
    def GetPrimitiveType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def IsEnumeration(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ConvertEnumerationValuesToInts(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def FixEnumerations(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetIsFileFromRoot(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetIsFileFromRoot(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VariableSaveListExtensionMethods(typing.Any):
    def GetVariableSave(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VariableListSaveExtensionMethods(typing.Any):
    def GetTypeConverter(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <get_AllStates>d__47(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class GumxVersions(int): ...

class <>c__DisplayClass148_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass149_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass150_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass152_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass153_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <get_AllElements>d__107(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass1_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass1_1(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass2_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass2_1(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass5_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass1_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass8_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VariableContainerType(int): ...

class <>c__DisplayClass21_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass22_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass7_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass8_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass8_1(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
