using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Media;

namespace Gum.Avalonia.Themes;

/// <summary>
/// The tool's chrome icons in the Avalonia head: the geometries the WPF head uses, read from
/// <c>Gum/Themes/GumIcons.xaml</c> (generated by <c>GumFigmaIconRipper</c>), embedded unchanged.
/// Keys are the SVG file names; a key with a <c>.Secondary</c> twin is two-tone.
/// </summary>
public static class GumIconGeometries
{
    private const string ResourceName = "Gum.Avalonia.Themes.GumIcons.xaml";
    private static readonly XNamespace XamlNamespace = "http://schemas.microsoft.com/winfx/2006/xaml";
    private static readonly Lazy<Dictionary<string, string>> PathData = new Lazy<Dictionary<string, string>>(LoadPathData);
    private static readonly Dictionary<string, Geometry> Cache = new Dictionary<string, Geometry>();

    /// <summary>Every geometry key, including the <c>.Secondary</c> ones.</summary>
    public static IReadOnlyCollection<string> Keys => PathData.Value.Keys;

    /// <summary>The geometry for <paramref name="key"/> in a 32x32 box, or null when there is none.</summary>
    public static Geometry? Get(string key)
    {
        if (Cache.TryGetValue(key, out Geometry? cached))
        {
            return cached;
        }
        if (!PathData.Value.TryGetValue(key, out string? data))
        {
            return null;
        }

        Geometry geometry = StreamGeometry.Parse(data);
        Cache[key] = geometry;
        return geometry;
    }

    private static Dictionary<string, string> LoadPathData()
    {
        using Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException($"{ResourceName} is not embedded in the head.");
        XDocument document = XDocument.Load(stream);

        Dictionary<string, string> result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (XElement geometry in document.Descendants().Where(element => element.Name.LocalName == "PathGeometry"))
        {
            if (geometry.Attribute(XamlNamespace + "Key")?.Value is not { } key ||
                geometry.Attribute("Figures")?.Value is not { } figures)
            {
                continue;
            }

            // The path mini-language's fill-rule prefix: F0 is even-odd, F1 non-zero.
            string fillRule = geometry.Attribute("FillRule")?.Value == "EvenOdd" ? "F0 " : "F1 ";
            result[key] = fillRule + figures;
        }
        return result;
    }
}

/// <summary>
/// Draws one chrome icon (<see cref="Icon"/>, a <see cref="GumIconGeometries"/> key) in the inherited
/// foreground brush, with its secondary tone at <see cref="SecondaryOpacity"/>. The counterpart of the
/// WPF <c>GumIcon</c>; it takes on the theme's color from the button or text around it.
/// </summary>
public sealed class GumIcon : Control
{
    /// <summary>Opacity of a two-tone icon's secondary geometry.</summary>
    public const double SecondaryOpacity = 0.32;

    private const double GeometrySize = 32;
    private const double DefaultSize = 16;

    /// <summary>Defines the <see cref="Icon"/> property.</summary>
    public static readonly StyledProperty<string?> IconProperty =
        AvaloniaProperty.Register<GumIcon, string?>(nameof(Icon));

    static GumIcon()
    {
        AffectsRender<GumIcon>(IconProperty, TextElement.ForegroundProperty);
        AffectsMeasure<GumIcon>(IconProperty);
    }

    /// <summary>The icon's key, the SVG file name it was generated from (e.g. "AnchorTopLeft").</summary>
    public string? Icon
    {
        get => GetValue(IconProperty);
        set => SetValue(IconProperty, value);
    }

    /// <inheritdoc/>
    protected override Size MeasureOverride(Size availableSize) =>
        new Size(double.IsNaN(Width) ? DefaultSize : Width, double.IsNaN(Height) ? DefaultSize : Height);

    /// <inheritdoc/>
    public override void Render(DrawingContext context)
    {
        if (Icon is not { } key || GumIconGeometries.Get(key) is not { } primary)
        {
            return;
        }

        IBrush brush = TextElement.GetForeground(this) ?? Brushes.White;
        double scale = Math.Min(Bounds.Width, Bounds.Height) / GeometrySize;
        using (context.PushTransform(Matrix.CreateScale(scale, scale)))
        {
            context.DrawGeometry(brush, null, primary);
            if (GumIconGeometries.Get(key + ".Secondary") is { } secondary)
            {
                using (context.PushOpacity(SecondaryOpacity))
                {
                    context.DrawGeometry(brush, null, secondary);
                }
            }
        }
    }
}
