from __future__ import annotations
import typing
from typing import Any


class NetworkManager(typing.Any):
    Self: typing.Any
    def DownloadWithProgress(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToMemoryDisplay(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
