from __future__ import annotations
import typing
from typing import Any


class ElementSaveExtensions(typing.Any):
    CustomCreateGraphicalComponentFunc: typing.Any
    def RegisterGueInstantiationType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RegisterGueInstantiation(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def RegisterDefaultInstantiationType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def CreateGueForElement(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToGraphicalUiElement(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetStatesAndCategoriesRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddStatesAndCategoriesRecursivelyToGue(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def CreateGraphicalComponent(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def AddExposedVariablesRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetVariablesRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ValueEquality(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyVariableReferences(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyVariableReferences(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ApplyVariableReferencesOnSpecificOwner(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetRightSideAndState(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def SetGraphicalUiElement(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def CreateChildrenRecursively(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Reset(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class InstanceSaveExtensionMethods(typing.Any):
    def ToGraphicalUiElement(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class VariableReferenceAssignmentResult(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass23_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass25_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...

class <>c__DisplayClass29_0(typing.Any):
    def Equals(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetHashCode(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def GetType(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
    def ToString(self, *args: typing.Any, **kwargs: typing.Any) -> typing.Any: ...
