using System.Collections.Generic;
using Gum.DataTypes;
using Gum.DataTypes.Variables;
using GumRuntime;

namespace Gum.ProjectServices;

/// <inheritdoc/>
public class ReferencePropagationService : IReferencePropagationService
{
    /// <inheritdoc/>
    public DetectUnpropagatedReferencesResult Detect(GumProjectSave project)
    {
        DetectUnpropagatedReferencesResult result = new DetectUnpropagatedReferencesResult();

        foreach (ElementSave element in EnumerateProjectElements(project))
        {
            List<StateSave> states = element.GetStatesWithUnpropagatedReferences();
            if (states.Count > 0)
            {
                result.Elements.Add(new ElementWithUnpropagatedReferences
                {
                    Element = element,
                    States = states
                });
            }
        }

        return result;
    }

    /// <inheritdoc/>
    public IReadOnlyList<ElementSave> PropagateReferences(GumProjectSave project)
    {
        List<ElementSave> modified = new List<ElementSave>();

        foreach (ElementSave element in EnumerateProjectElements(project))
        {
            List<StateSave> states = element.GetStatesWithUnpropagatedReferences();
            if (states.Count == 0)
            {
                continue;
            }

            foreach (StateSave state in states)
            {
                element.ApplyVariableReferences(state);
            }

            modified.Add(element);
        }

        return modified;
    }

    private static IEnumerable<ElementSave> EnumerateProjectElements(GumProjectSave project)
    {
        // StandardElements are intentionally skipped. The standards generated by
        // StandardElementsManager contain VariableReferences whose evaluated values
        // equal the type default (e.g. Text.Tiny → IsBold = Styles.Tiny.IsBold,
        // resolved to false). The save pipeline elides default-valued scalars, so
        // the missing materialization is the correct on-disk state, not a propagation
        // failure. The AI-authoring failure mode this service targets lives in
        // user-authored Components and Screens.
        foreach (ScreenSave screen in project.Screens)
        {
            yield return screen;
        }
        foreach (ComponentSave component in project.Components)
        {
            yield return component;
        }
    }
}
