name: Build Windows MSI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Advanced Installer
      run: |
        choco install advanced-installer -y
      shell: powershell

    - name: Build .NET Project
      run: |
        msbuild Gum\Gum\Gum.csproj /p:Configuration=Release /p:Platform=AnyCPU
      shell: cmd

    - name: Build AIP to MSI
      run: |
        "C:\Program Files (x86)\Caphyon\Advanced Installer 21.5\bin\x86\AdvancedInstaller.com" /build "Gum\Gum\GumInstaller.aip"
      shell: cmd

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: Gum\Gum\bin\Installer\GumInstaller.msi