name: Build Windows MSI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Advanced Installer
      run: |
        choco install advanced-installer -y -q
      shell: powershell

    - name: Restore NuGet Packages
      run: |
        dotnet restore Gum.sln
      shell: cmd

    - name: Build .NET Project
      run: |
        dotnet build Gum.sln -c Release --no-restore -nologo -v q --property WarningLevel=0 -clp:ErrorsOnly
      shell: cmd

    - name: Build AIP to MSI
      run: |
      dir "C:\Program Files (x86)\Caphyon\Advanced Installer 22.7\"
      "C:\Program Files (x86)\Caphyon\Advanced Installer 22.7\AdvancedInstaller" /build "Gum\GumInstaller.aip"
      shell: cmd

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: Gum\bin\Installer\GumInstaller.msi