name: "Build Samples"

on: workflow_dispatch

jobs:
    Build-Samples:
        runs-on: windows-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup .NET SDKs
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x

            - name: Install .NET MAUI Workload
              run: dotnet workload install maui

            - name: Build Samples
              run: pwsh ./.github/scripts/build-all.ps1 -Path Samples
