  build:
    needs: list-solutions
    runs-on: windows-latest
    name: build (${{ matrix.solution }}, ${{ matrix.dotnet-version }})
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '8.0.x' ]
        solution: ${{ fromJson(needs.list-solutions.outputs.solutions) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      continue-on-error: false

    - name: Initialize Submodules
      run: git submodule update --init --recursive
      continue-on-error: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
      continue-on-error: false

    - name: Build Solution (${{ matrix.solution }})
      run: |
        $solutionFile = (Get-ChildItem -Path Samples -Recurse -Include "${{ matrix.solution }}.sln").FullName
        $solutionDir = Split-Path -Path $solutionFile -Parent
        Write-Host "Changing to solution directory: $solutionDir"
        Set-Location -Path $solutionDir
        Write-Host "Building solution: $solutionFile"
        dotnet restore "$solutionFile" -v q
        dotnet build "$solutionFile" --configuration Release --no-restore -nologo -v q --property WarningLevel=0 -clp:ErrorsOnly
      continue-on-error: false