name: Build All

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '8.0.x', '9.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Submodules
      run: git submodule update --init --recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Find and Restore Dependencies
      run: |
        Get-ChildItem -Path Samples -Recurse -Include *.sln | ForEach-Object { dotnet restore $_.FullName -v q }

    - name: Build All
      run: |
        Get-ChildItem -Path Samples -Recurse -Include *.sln | ForEach-Object { dotnet build $_.FullName --configuration Release --no-restore --nologo -v q --property WarningLevel=0 /clp:ErrorsOnly }